### ISSUE TITLE
When create dataset

### ISSUE THREAD

**Issue by xav12358** [loicmarie/hands-detection#2]
Hello,

When I try to execute that command 
`python3 create_inputs_from_dataset.py `

I get that error:
`python3 create_inputs_from_dataset.py 
Traceback (most recent call last):
  File "create_inputs_from_dataset.py", line 40, in <module>
    from utils import label_map_util
  File "./models/object_detection/utils/label_map_util.py", line 22, in <module>
    from object_detection.protos import string_int_label_map_pb2
ImportError: cannot import name 'string_int_label_map_pb2'`

Do I install wrong something?

**Comment by takashi-uesaka** [comment]
I got same error, but I found solution.
comment out 2 lines.

#LABEL_MAP_PATH = 'hands_label_map.pbtxt'
#label_map_dict = label_map_util.get_label_map_dict(LABEL_MAP_PATH)

Variable of label_map_dict is not used.

**Comment by xav12358** [comment]
I also had to remove that line:
        #classes.append(label_map_dict[label])

How do I simply run the example?

**Comment by zhengxw9** [comment]
find the answer here: https://github.com/tensorflow/models/issues/1969 
maybe need protoc to compile the model first
